/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROJECT32;

/**
 *
 * @author HP
 */
public class project32 extends javax.swing.JFrame {

    /**
     * Creates new form project32
     */
    public project32() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fgaji = new javax.swing.JTextField();
        fkendaraan = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fpajak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 55, 109));
        jPanel1.setLayout(new java.awt.BorderLayout(7, 0));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 215, 232));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAJAK");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(165, 215, 232));
        jPanel2.setLayout(new java.awt.BorderLayout(7, 7));

        jPanel4.setBackground(new java.awt.Color(165, 215, 232));
        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 7, 7));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 36, 71));
        jLabel2.setLabelFor(fgaji);
        jLabel2.setText("Gaji :");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 36, 71));
        jLabel3.setLabelFor(fkendaraan);
        jLabel3.setText("Kendaraan :");
        jPanel4.add(jLabel3);

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(165, 215, 232));
        jPanel5.setLayout(new java.awt.GridLayout(3, 0, 7, 7));

        fgaji.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fgaji.setForeground(new java.awt.Color(165, 215, 232));
        fgaji.setText("Masukkan Jumlah Gaji");
        fgaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgajiMouseClicked(evt);
            }
        });
        jPanel5.add(fgaji);

        fkendaraan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fkendaraan.setForeground(new java.awt.Color(165, 215, 232));
        fkendaraan.setText("Masukkan Jumlah Kendaraan Pribadi");
        fkendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fkendaraanMouseClicked(evt);
            }
        });
        jPanel5.add(fkendaraan);

        btnhitung.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnhitung.setForeground(new java.awt.Color(11, 36, 71));
        btnhitung.setText("Hitung Pajak");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        jPanel5.add(btnhitung);

        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(165, 215, 232));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 36, 71));
        jLabel4.setLabelFor(fpajak);
        jLabel4.setText("Pajak Yang Harus Dibayar :");
        jPanel3.add(jLabel4);

        fpajak.setEditable(false);
        fpajak.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fpajak.setForeground(new java.awt.Color(11, 36, 71));
        jPanel3.add(fpajak);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgajiMouseClicked
        // TODO add your handling code here
        if(fgaji.getText().equals("Masukkan Jumlah Gaji")){
            fgaji.setForeground(new java.awt.Color(11, 36, 71));
            fgaji.setText("");
        }
    }//GEN-LAST:event_fgajiMouseClicked

    private void fkendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkendaraanMouseClicked
        // TODO add your handling code here:
        if(fkendaraan.getText().equals("Masukkan Jumlah Kendaraan Pribadi")){
            fkendaraan.setForeground(new java.awt.Color(11, 36, 71));
            fkendaraan.setText("");
        }
    }//GEN-LAST:event_fkendaraanMouseClicked

    public void clear(){
        fpajak.setText("");
    }
    
    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        clear();
        Integer gaji = Integer.parseInt(fgaji.getText());
        Integer kendaraan = Integer.parseInt(fkendaraan.getText());
        
        if(gaji >= 10000000 && kendaraan >= 3){
            Double pajak = (double) gaji * 0.15;
            int pjk = (int) Math.floor(pajak);
            fpajak.setText(Integer.toString(pjk));
        }else if (gaji >= 5000000){
            if(kendaraan == 2){
                Double pajak = (double) gaji * 0.1;
                int pjk = (int) Math.floor(pajak);
            fpajak.setText(Integer.toString(pjk));
            }else if (kendaraan == 1){
                Double pajak = (double) gaji * 0.07;
                int pjk = (int) Math.floor(pajak);
                fpajak.setText(Integer.toString(pjk));
            }else if (kendaraan < 1){
                fpajak.setText("Gaji Anda " + Integer.toString(gaji) + " Maka Masukkan Jumlah Kendaraan");
            }else if (kendaraan >= 3){
                fpajak.setText("Apakah Benar Gaji Anda " + Integer.toString(gaji));
            }
        }else if (gaji < 5000000){
            if(kendaraan == 1){
                Double pajak = (double) gaji * 0.05;
                int pjk = (int) Math.floor(pajak);
                fpajak.setText(Integer.toString(pjk));
            }else if (kendaraan == 0){
                Double pajak = (double) gaji * 0.025;
                int pjk = (int) Math.floor(pajak);
                fpajak.setText(Integer.toString(pjk));
            }else if (kendaraan >= 2){
                fpajak.setText("Apakah Benar Gaji Anda " + Integer.toString(gaji));
            }
        }
        
    }//GEN-LAST:event_btnhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project32().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JTextField fgaji;
    private javax.swing.JTextField fkendaraan;
    private javax.swing.JTextField fpajak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
